export const MIN_SUBJECT_PRICE_VND = 10_000;
export const DEFAULT_MIN_PUBLISHED_QUESTIONS_FOR_GO_LIVE = 200;
export const DEFAULT_MIN_APPROVED_TEMPLATES_FOR_GO_LIVE = 1;
export const DEFAULT_FREE_TIER_LIMIT = 20;
export const DEFAULT_STUDY_TIER_LIMIT = 5;
